public with sharing class MCArray2 {

    @AuraEnabled
    public List<String> productsDetail {get; set;}
    
    @AuraEnabled
    public String Output1Array2 {get; set;}

    
    @AuraEnabled
    public String Output2Array2 {get; set;}

    
    @AuraEnabled
    public String Output3Array2 {get; set;}

    
    @AuraEnabled
    public List<String> Output4Array2 {get; set;}

    
    @AuraEnabled
    public List<String> Output5Array2 {get; set;}

    
    @AuraEnabled
    public List<String> Output6Array2 {get; set;}

    
    @AuraEnabled
    public List<String> Output7Array2 {get; set;}
}