public with sharing class MCArray1 {

    @AuraEnabled
    public List<String> recipients {get; set;}

    @AuraEnabled
    public String Output1Array1 {get; set;}

    
    @AuraEnabled
    public String Output2Array1 {get; set;}

    
    @AuraEnabled
    public String Output3Array1 {get; set;}

    @AuraEnabled
    public String TEST {get; set;}

    @AuraEnabled
    public Integer Output4Array1 {get; set;}

    
    @AuraEnabled
    public List<String> Output5Array1 {get; set;}

    
    @AuraEnabled
    public List<String> Output6Array1 {get; set;}

    
    @AuraEnabled
    public List<String> Output7Array1 {get; set;}

    @AuraEnabled    
    public KeyValueClass value {get; set;}
}